result <- readLines("sam1.txt")  
result2 <- readLines("sam2.txt")
result3 <- readLines("sam3.txt")
result4 <- readLines("sam4.txt")
result5 <- readLines("sam5.txt")
result6 <- readLines("sam6.txt")
result7 <- readLines("sam7.txt")
result8 <- readLines("sam8.txt")
result9 <- readLines("sam9.txt")
result10 <- readLines("sam10.txt")

a1 <- getMorph(result, "VV")
a2 <- getMorph(result2, "VV")
a3 <- getMorph(result3, "VV")
a4 <- getMorph(result4, "VV")
a5 <- getMorph(result5, "VV")
a6 <- getMorph(result6, "VV")
a7 <- getMorph(result7, "VV")
a8 <- getMorph(result8, "VV")
a9 <- getMorph(result9, "VV")
a10 <- getMorph(result10, "VV")

a1 <- unique(a1)
a2 <- unique(a2)
a3 <- unique(a3)
a4 <- unique(a4)
a5 <- unique(a5)
a6 <- unique(a6)
a7 <- unique(a7)
a8 <- unique(a8)
a9 <- unique(a9)
a10 <- unique(a10)

a1 <- paste0(a1,"다")
a2 <- paste0(a2,"다")
a3 <- paste0(a3,"다")
a4 <- paste0(a4,"다")
a5 <- paste0(a5,"다")
a6 <- paste0(a6,"다")
a7 <- paste0(a7,"다")
a8 <- paste0(a8,"다")
a9 <- paste0(a9,"다")
a10 <- paste0(a10,"다")

all <- c(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10)
all_verb <- unique(all)
write.csv(all_verb,"all_verb.csv")
